baseURL = 'https://ralphwyld.com'
languageCode = 'en-us'
title = 'Ralph Wyld'

[params]
author = "Ralph Wyld"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 1

  [[menu.main]]
  name = "Gigs"
  pageRef = "/gigs"
  weight = 2

 
  [[menu.main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 3


#	Music page to return soon
#  [[menu.main]]
#  name = "Music"
#  pageRef = "/music"
#  weight = 3
