[build]
  command = "./scripts/generate-lastmod.sh || true && hugo"
  publish = "public"
  

[context.production.environment]
  HUGO_VERSION = "0.147.8"
  HUGO_EXTENDED = "true"  
  
 [functions]
  directory = "netlify/functions"

  [functions."daily-build"]
  schedule = "@daily"
  
  [[redirects]]
	from = "/*"
	to = "/404/"
	status = 404